name: TouchscreenHolograms
main: me.filoghost.touchscreenholograms.TouchscreenHolograms
version: ${project.version}
api-version: 1.13

softdepend: [HolographicDisplays]

commands:
  touch:
    description: TouchscreenHolograms main command.
    usage: /<command> (Startup error)
    aliases: [touchholograms, touchhologram, th]